"""Write the generated C sources: per-chunk code files, function table, import table."""
import collections
import json
from pathlib import Path

from .lifter import FunctionLifter
from .symbols import load_symbols, import_thunks


def emit_all(ana, out_dir, funcs_per_file=60):
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    img = ana.img
    entries = sorted(ana.funcs)
    name_of = {e: f"f_{e:08X}" for e in entries}

    hdr = ["/* generated by ircrecomp - do not edit */", "#pragma once", '#include "cpu.h"']
    hdr += [f"void {name_of[e]}(CPU *c);" for e in entries]
    symbols = {va: v for va, v in load_symbols().items() if va in ana.funcs} if img.base == 0x400000 else {}
    thunks = import_thunks(ana)
    if symbols:
        hdr.append("")
        hdr.append("/* readable names for known functions (symbols/ral481.sym) */")
        hdr += [f"#define {n} f_{va:08X}" for va, (n, _) in sorted(symbols.items())]
    for va, n in sorted(thunks.items()):
        pass
    (out / "funcs.h").write_text("\n".join(hdr) + "\n")

    traps = []
    lines_total = 0
    files = []
    for chunk_no in range(0, len(entries), funcs_per_file):
        chunk = entries[chunk_no:chunk_no + funcs_per_file]
        src = ["/* generated by ircrecomp - do not edit */", '#include "funcs.h"', '#include "lifted.h"', ""]
        for e in chunk:
            fl = FunctionLifter(ana, e, name_of, symbols, thunks)
            src += fl.emit()
            src.append("")
            traps += fl.traps
        fname = f"code_{chunk_no // funcs_per_file:03d}.c"
        (out / fname).write_text("\n".join(src) + "\n")
        files.append(fname)
        lines_total += len(src)

    tbl = ["/* generated by ircrecomp - do not edit */", '#include "funcs.h"', "",
           "const FuncEntry g_func_table[] = {"]
    tbl += [f"    {{0x{e:08X}u, {name_of[e]}}}," for e in entries]
    tbl += ["};", f"const unsigned g_func_count = {len(entries)};", ""]
    # imports: IAT slot address + dll + name, in a fixed order the runtime binds by name
    tbl.append("const ImportEntry g_import_table[] = {")
    for va, dll, name in img.imports:
        tbl.append(f'    {{0x{va:08X}u, "{dll}", "{name}"}},')
    if not img.imports:
        tbl.append('    {0u, "", ""},')
    tbl += ["};", f"const unsigned g_import_count = {len(img.imports)};", ""]
    tbl.append(f"const uint32_t g_image_base = 0x{img.base:08X}u;")
    tbl.append(f"const uint32_t g_image_size = 0x{img.size:08X}u;")
    tbl.append(f"const uint32_t g_entry_point = 0x{img.entry:08X}u;")
    (out / "table.c").write_text("\n".join(tbl) + "\n")
    files.append("table.c")

    (out / "sources.cmake").write_text(
        "set(GEN_SOURCES\n" + "\n".join(f"    ${{CMAKE_CURRENT_LIST_DIR}}/{f}" for f in files) + "\n)\n")

    trap_kinds = collections.Counter(t[1].split(" (")[0].split(" ")[0] for t in traps)
    report = {"stats": ana.stats(), "c_lines": lines_total, "files": len(files), "named_functions": len(symbols),
              "traps": len(traps), "trap_kinds": trap_kinds.most_common(),
              "trap_sites": [(f"{va:#x}", why) for va, why in traps[:400]]}
    (out / "lift_report.json").write_text(json.dumps(report, indent=1))
    return report
